### ISSUE TITLE
PackageKit fails to update (no such file or directory for appstream in /var/cache)

### ISSUE THREAD

**Issue by TheLastProject** [taw00/riot-rpm#14] opened 2018-05-21 13:46 UTC
The reply on this issue implies it may be an issue with this repo? https://bugzilla.redhat.com/show_bug.cgi?id=1580162#c1

**Comment by taw00** [comment] 2018-05-27 05:10
I commented in that bugzilla issue. I'm not sure I grok the error. Will continue to monitor. Thanks for the heads up.

**Comment by imaginaryusername** [comment] 2018-10-31 04:14
Probably experiencing the same issue: "PK error: "Error when getting information for file “/var/cache/PackageKit/28/metadata/taw-Riot/repodata/....."

**Comment by taw00** [comment] 2018-12-02 06:02
I can't reproduce this error. Whacky.

**Comment by taw00** [comment] 2018-12-13 04:25
Okay. I triggered this with an extension install via packagekit.
I fixed it with `pkcon repair` ala https://ask.fedoraproject.org/en/question/122198/how-to-find-why-packagekit-complain-about-a-missing-file/

I'm closing this, but re-open if you can't fix it. *why* does it occur? I don't know. But I seem to have remedied it.

**Closed as completed by taw00** 2018-12-13 04:25 UTC
